services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

  pma:
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    restart: on-failure:10
    depends_on:
      - db

  web:
    image: nginx
    volumes: 
      - ./Webseite:/usr/share/nginx/html:ro  # ist ein Bind
    # The following volume format is also valid but commented out for this example:
    #- type: bind
    #  source: ./Webseite
    #  target: /usr/share/nginx/html # './' muss nicht angegeben werden, da 'type: bind' definiert wurde
    #  read_only: false
    # No ports configuration to avoid conflicts

    deploy: 
      replicas: 2

  wp:
    image: wordpress
    environment:
      - WORDPRESS_DB_Host=db:3306
      - WORDPRESS_DB_USER=blog
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=blog
    prots:
      - 8081:80
    restart: always
    depends_on:
      -db
volumes:
  mariadb:
    name: mariadb_2
  wp_data:
    name: wp_data_3
